name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: code review
      run: |
        find . -name '*.py' -print -exec pylint {} \;
        # fails the build if one file has pylint score below 7.0
    - name: Analyse code
      run: |
        for file in */*.py; do pylint "$file" --fail-under=7.0; done

